version: '3'

services:
  stockwise:
    build:
      context: .
      dockerfile: Dockerfile
    image: stockwise
    container_name: stockwise-container
    ports:
      - "8000:8000"
    volumes:
      - stockwise_data:/app/static
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DB_PATH=/app/static/database.db
      - TZ=America/Chicago
    restart: always
    networks:
      - stockwise_network
  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: stockwise-nginx
    environment:
      - TZ=America/Chicago
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - stockwise
    restart: always
    networks:
      - stockwise_network
  # SMTP Service
  smtp:
    image: boky/postfix
    container_name: stockwise-smtp
    environment:
      - HOSTNAME=stockwise-smtp.local
      - TZ=America/Chicago
    ports:
      - "25:25"
    restart: always
    networks:
      - stockwise_network

networks:
  stockwise_network:
    driver: bridge

volumes:
  stockwise_data:
    name: stockwise_data