name: stockwise  # Add this at the top of the file
version: '3'

services:
  stockwise:
    build:
      context: .
      dockerfile: Dockerfile
    dns:
      - 8.8.8.8
      - 8.8.4.4
    image: stockwise
    container_name: stockwise-container
    ports:
      - "80:8000"
    volumes:
      - stockwise_data:/app/static
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DB_PATH=/app/static/database.db
      - TZ=America/Chicago
      - SMTP_HOST=smtp
      - SMTP_PORT=25
    restart: always
    networks:
      stockwise_network:
        aliases:
          - stockwise.local
    # Add these network options
    dns_search: .
    dns_opt:
      - ndots:1


  # Nginx reverse proxy
  # nginx:
  #   image: nginx:alpine
  #   container_name: stockwise-nginx
  #   environment:
  #     - TZ=America/Chicago
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #     - ./nginx/ssl:/etc/nginx/ssl:ro
  #     - ./nginx/logs:/var/log/nginx
  #   depends_on:
  #     - stockwise
  #   restart: always
  #   networks:
  #     - stockwise_network


  # SMTP Service
  smtp:
    image: namshi/smtp
    container_name: stockwise-smtp
    environment:
      - HOSTNAME=tianshen.store
      - MAILNAME=tianshen.store
      - RELAY_NETWORKS=:0.0.0.0/0
      - RELAY_FROM_HOST=tianshen.store
      - START_TLS=yes
    ports:
      - "25:25"
    networks:
      - stockwise_network

networks:
  stockwise_network:
    driver: bridge
    name: stockwise_network

volumes:
  stockwise_data:
    name: stockwise_data